image: silkeh/clang:11

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
     - apt update && apt -y install make cmake
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=DEBUG
    - make
  artifacts:
    paths:
      - build/src/gndb
    cache:
        paths:
           - find . -name '*.o'

# run tests using the binary built before
test:
  stage: test
  script:
    - cd build
    - make test
    - llvm-cov gcov -l -p find ../src -name '*.gcno'
